name = "GeometricMultigrid"
uuid = "ec3bce20-3e4b-4d8a-a801-89defc82be1c"
authors = ["Gabriel Weymouth <gabriel.weymouth@gmail.com> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.2"
